version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn thoughtsapi.wsgi --reload -c gunicorn.py
    env_file: .env
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - aws-local
      - redis
      - postgres
    networks:
      - thoughts-api-network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A thoughtsapi worker -l DEBUG
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - aws-local
      - redis
      - postgres
    networks:
      - thoughts-api-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - thoughts-api-network

  aws-local:
    image: localstack/localstack
    ports:
      - 4566
    environment:
      - HOSTNAME_EXTERNAL=aws-local
      - SERVICES=sqs
    networks:
      - thoughts-api-network

  postgres:
    image: postgres:10.6
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=thoughts
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - thoughts-api-network

volumes:
  postgresql_data:
  redis_data:


networks:
  thoughts-api-network:
    driver: bridge
