version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - redis
    networks:
      - thoughts-api-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - thoughts-api-network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A thoughtsapi worker -l DEBUG
    volumes:
      - ./:/app
    depends_on:
      - redis
    networks:
      - thoughts-api-network

volumes:
  redis_data:

networks:
  thoughts-api-network:
    driver: bridge
